include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_empty_else: true
    avoid_print: false
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    empty_statements: true
    hash_and_equals: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    prefer_relative_imports: true
    test_types_in_equals: true
    unnecessary_statements: true
    use_key_in_widget_constructors: false
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_as: false
    avoid_catches_without_on_clauses: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_js_rounded_ints: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: false
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_this: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    await_only_futures: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    flutter_style_todos: true
    overridden_fields: true